### ISSUE TITLE
MAtmos for 1.8.9 resource pack incompatibility

### ISSUE THREAD

**Issue by Bo-Fone** [Sollace/MAtmos#10]
Hey Sollace,

I just downloaded the MAtmos.Default and MSI Conversion under the latest 1.8.9 version. However they show up as resource pack for 1.9 and says incompatible for 1.8.9.

**Comment by Sollace** [comment]
You can ignore that, the packs say they're compatible with 1.9 to avoid the message in the version. It doesn't actually make any difference.
