### ISSUE TITLE
1.11 compatibility

### ISSUE THREAD

**Issue by GVG** [Sollace/MAtmos#11]
Can anyone update MAtmos for Minecraft 1.11? Unfortunately the trick like with 1.10.2 doesn't work for 1.11.

**Comment by GVG** [comment]
Update is ready and will be committed ASAP.

**Comment by supergvg** [comment]
Small fix for 1.11 already in the repository.

**Comment by GVG** [comment]
SuperGVG and I continue working on this project in this fork https://github.com/supergvg/MAtmos
There is 1.11 build and we are going to merge it with Presence Footsteps mod in next release.
