### ISSUE TITLE
decrease volume of wind sounds

### ISSUE THREAD

**Issue by 0Navis0** [Sollace/MAtmos#14]
The wind sounds should be drastically decreased compared to other sounds because it's really too loud and it override almost all the other sounds.

**Comment by DrakoAlcarus** [comment]
Something that my help you is to get Audacity and open the sounds in that app. Then change the volume of the wind .ogg files themselves and save and exchange the files. Just a heads up, copy the matmos default folder just in case.

I'm sure I'm super late, but hopefully this helped a bit.
