### ISSUE TITLE
Compatibility for Minecraft 1.12.2

### ISSUE THREAD

**Issue by andreaspalmer** [Sollace/MAtmos#15]
Hi there, will there be a relase for Matmos for the latest update of Minecraft to 1.12.2?
Thanks

**Comment by k9lego** [comment]
That seriously would be great!

**Comment by DrakoAlcarus** [comment]
I was wondering too. The default matmos soundpack is one of my absolute favorites and I like Matmos far better than Dynamic Surroundings. Going to bump this since it hasn't had an activity in a while.

**Comment by k9lego** [comment]
I'm still keeping my eye on this :)
Hopefully you will update it. Preferably just skip to 1.13 at this point.

**Comment by Sollace** [comment]
A 1.13 update is still a long way's out because I still have to wait for dev tools  and liteloader to become stable, so it'll be only 1.12.2 at this point.

**Comment by andreaspalmer** [comment]
I'm still be hyped for either versions! :D This is by far my favourite mod of all times.

**Comment by DrakoAlcarus** [comment]
I don't mind that at all. I wanted it for my 1.12 pack, as 1.13 is meh, and most mods aren't ready for it.

**Comment by xJon** [comment]
It seems like there was some 1.12.2 work on the mod, just wondering whether i will ever get released or not...

**Comment by Sollace** [comment]
Sorry, I can't give a time frame yet. The code has been updated, I just haven't been able to test it yet.

**Comment by xJon** [comment]
No problem @Sollace :) 
It will be wonderful whenever you get to it.

**Comment by k9lego** [comment]
Agreed!

**Comment by Sollace** [comment]
https://github.com/Sollace/MAtmos/releases/tag/r37

**Comment by xJon** [comment]
@Sollace That's awesome! Thank you.
Also nice pick for the resource pack logo.
