### ISSUE TITLE
Wondering if 1.12.2 Version is Planned

### ISSUE THREAD

**Issue by DrakoAlcarus** [Sollace/MAtmos#16]
This is a clone of #15 , but I was wondering if it had any notice taken on it. I absolutely love the matmos default pack and would love to hear those fantastic sounds again. I feel like Matmos does better than dynamic surroundings as well, as the sounds are just so much richer. And nostalgic to players that played Tekkit, so i can't help myself but to flock back to matmos after so much time.

Also, liteloader is in fact 1.12.2 updated!

Excited to hear good news,
Vahnae

**Comment by Sollace** [comment]
I've stopped working on this mod and have no current plans to update it. There should be another version available, because I remember someone picked up both this and PF after I left.

**Comment by DrakoAlcarus** [comment]
Do you know where to look? All I really see is a pull request for minecraft v1.11 and googling gets me Dynamic Surroundings or malware loaded sites that have a renamed version.

The next best thing is to try and ask OreCruncher how to make his mod work with the old matmos pack, or update it myself, that of which may take time, as I don't know java very well, and haven't coded for a very long time. Or very much. :v

**Comment by Sollace** [comment]
If I get some time, I'll try updating it. IIRC Dynamic Surroundings is the successor to both this and PF, but it requires Minecraft Forge.

**Comment by DrakoAlcarus** [comment]
That would be insanely appreciated! Take your time on it. I put all my eggs in one basket and asked Orecruncher about adding new sounds and sound events as well, but he hasn't responded as of yet. Can't remember if he had a page on it, tho...

**Comment by DrakoAlcarus** [comment]
Lost a few of those eggs: OreCruncher hasn't yet figured out a way to add
resource pack support. Again, thank you so much for being willing to do
this. It means a lot to every fan of this great mod.

**Comment by DrakoAlcarus** [comment]
When it gets updated, how would I install the mod? It's been a while since I messed around with any lite loader stuff.

**Comment by Sollace** [comment]
@DrakoAlcarus It should be the same as it's always been. Download the liteloader installer, run that, then put the matmos.litemod into the /mods/1.12.2 folder.

**Comment by DrakoAlcarus** [comment]
That's fair. Where do I get the matmos.litemod folder at? Is in in the
downloadable zip?

**Comment by DrakoAlcarus** [comment]
I still haven't found the matmos.litemod. Am I downloading everything wrong, or am I looking in the wrong places?

**Comment by Sollace** [comment]
The litemod is not released yet. When it is there'll be a download for it from the releases page

**Comment by DrakoAlcarus** [comment]
Alright,  thanks for the heads up!

**Comment by DrakoAlcarus** [comment]
I came back from the dead! I gave up modding 1.12, and went back to good ol 1.7.10. I can finally run Matmos, but I did have a question. Matmos Default plays the high altitude wind sounds everywhere except underground
