### ISSUE TITLE
1.7.10 Download Links Broken

### ISSUE THREAD

**Issue by DarianLStephens** [Sollace/MAtmos#20]
On the download page, the releases for 1.7.10 lead to a 'Page Not Found' error on Github, and looking in the Releases section, only the source code is able to be found.

If you don't have a backup, and don't want to compile it again, I've got both Version 29ub4 and 29ub4.5.

**Comment by Sollace** [comment]
Oh yeah. They're gone because @dags- deleted his repository.

If you upload them here I'll gladly update the wiki page.

**Comment by DarianLStephens** [comment]
I'd be happy to.
Github complains about trying to upload .jar file types, so they're both in an archive:
[MAtmos 1.7.zip](https://github.com/Sollace/MAtmos/files/4301306/MAtmos.1.7.zip)
In case you're interested, I also downloaded the v29ub4 (Though unfortunately not v29ub4.5) source:
[MAtmos-1.7.10-v29ub4.zip](https://github.com/Sollace/MAtmos/files/4301307/MAtmos-1.7.10-v29ub4.zip)
I don't know what version you have on your source, but I wouldn't be surprised if yours was the latest.

**Comment by Sollace** [comment]
Thanks!

https://github.com/Sollace/MAtmos/releases/tag/r29d
