### ISSUE TITLE
Multiple bugs with default expansion pack

### ISSUE THREAD

**Issue by Brottweiler** [Sollace/MAtmos#3]
There are several bugs that are not breaking, but annoying, that should be fixed in the [Default Expansion Pack](https://github.com/Sollace/MAtmos/releases/download/r30c/Matmos.Default.zip).
- [ ] When standing in water with feet only, it sounds like you are under water with head
- [ ] Drawing back bow and instantly switching from the bow, still plays the entire "bow string drawback" sound. This was fixed in Rhapsodia when I reported it there, since it had a similar bug.
- [ ] Critical hit sound when punching sounds even if you don't get the crits;
  - When you jump upwards and punch, you hear them. You only get crits when you punch and you fall downwards after jumping.
  - In 1.9, you can only get critical hits when not sprinting, yet if you sprint and jump and punch, you hear crit sounds.
- [ ] When shooting a full power arrow (and getting the crit trail) it does not always give you the crit sound. 
  - It only gives crit sound if you wait a little bit longer before you release the bow. If you release the bow as soon you get to the 3rd state, and get the crit trail, it won't give crit sound. Wait 1 second longer before releasing, then you get crit sound.
- [ ] When punching blocks with sword it plays the "sword hit sound" (this sound should only be heard for players).
- [ ] When holding down the button to mine blocks using sword, it repeatetly plays the "sword hit sound".
- [ ] Axes and other things can be used as weapons (axe is an encouraged weapon now), and it does not have the "sword hit sound" like the sword does.
- [ ] Opening container with sword (or I guess other tools) produce the "sword hit sound".
- [ ] No matter the altitude, outside always have really strong wind sounds. (Thanks @Patrick13542)

Will fill with more bugs as I find or remember them.

**Comment by Sollace** [comment]
This probably has to do with the fact that all I've done is translate the old default pack to json so it will work with the new version.

I know next to nothing about how Matmos' resourcepacks work. The whole thing is one giant heaping mess, so I don't know if I can fix any of this.

If you can figure it out you're welcome to try. I'll happily include any changes you make and credit in the release.

**Comment by Brottweiler** [comment]
Yeah, we can probably see if there are someone on the forums that might be able to help, too. I don't really know how they work, either, hehe.

**Comment by Patrick13542** [comment]
I have been experiencing an issue that isn't on this list. Wherever I am, no matter the altitude, I hear the wind sound. It's very unpleasant. Anyone else having this issue??

**Comment by Brottweiler** [comment]
@Patrick13542 Yes, I hear wind a lot too, so much that I think maybe I am hearing it too much... So you are right. I hear wind almost anywhere outside, and it really sounds like I am always high up. I will add it.

**Comment by Brottweiler** [comment]
Moved to https://github.com/supergvg/MAtmos/issues/2
