### ISSUE TITLE
download confusion

### ISSUE THREAD

**Issue by mvdhoning** [Sollace/MAtmos#4]
where is the place to download the 1.7.10 minecraft version of this mod with the default resource pack?
the 1.7.10 download from here refers to the dags repo and the default resource pack download cannot be found (by me). The default resource pack does not seem to come with the mod download as the wiki suggests. Going manualy to the following page seems to give newer releases of the mod pack along with a downloadeable default matmos resource pack. https://github.com/Sollace/MAtmos/releases
It does seem to work with the latest 1.7.10 mod release from dags repo. (at least it does not crash and seems to randomly play sounds).

Unfortunately default minecraft audio sounds stopped working after i got the random matmos sounds. E.g. i could not hear footsteps etc. anymore until i removed the matmos mod. Dont know if that is caused by the matmos mod on its own or the default matmos resource pack not belonging to the 1.7.10 version of the mod but for the 1.9 version of minecraft.

**Comment by Brottweiler** [comment]
http://minecraft.ha3.eu/matmos/download.php

**Comment by Sollace** [comment]
Dagg's version never had a default resourcepack. That's something I had to fix as soon as I took over.

I don't even know what people used to use with his but I think Rhapsodia still works. You can try that one.

Why game sounds wouldn't work, I have no idea. I never came across that problem with his version.

**Comment by Brottweiler** [comment]
@Sollace I think the only thing around 1.7.10 was the MSI converted pack, which should be available [here](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1290798-1-6-2-minecraft-sound-improvement-custom-music-a?comment=114).

There also [this one](http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/1274487-matmos-environmental-sound-atmosphere-simulator?comment=3901).

**Comment by Sollace** [comment]
@Brottweiler Ok, thanks. I've added those two to the wiki.
