### ISSUE TITLE
problem with Minecraft Vanilla songs added by Matmos

### ISSUE THREAD

**Issue by 0Navis0** [Sollace/MAtmos#5]
The songs added by Matmos for the Vainlla songs doesn't work properly. I explain me with an example because it's a bit diffucult to explain. But for example MSI adds to the mob.villager.idle songs something like almost 100 ambiance songs for them, but Minecraft totally ignores it and only take the 3 first ones because they overwrites the default Minecraft Vanilla songs. This thing is the same with the mob.zombie.say, the mob.cow.say and mob.chicken.say. The songs should be played with the Vanilla ones but are totally ignored. Minecraft only plays the songs wich overwrite the Vanilla songs.

**Comment by Sollace** [comment]
And vanilla sounds added have to be correctly registered in sounds.json, otherwise the game's not going to recognise them. This has nothing to do with MAtmos.

**Comment by 0Navis0** [comment]
I know, I spoke about the songs that the ressourcepack MSI adds and overwrites for the Vanilla sounds, they don't work.
Only the songs wich overwrites the Vanilla songs are played, not the ones wich are added in more.

**Comment by Sollace** [comment]
Well that's not really something I can help with.
